name: namma_metro_app
description: A Namma Metro Flutter app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/metro_banner.jpeg
    - assets/map_image.jpeg   # ✅ Add your map image here
